#!/usr/bin/env bash

TARGET_DIR="${1}"
shift || true

if [[ ! -d "${TARGET_DIR}" ]]; then
  echo "Error: TARGET_DIR '${TARGET_DIR}' does not exist or is not a directory." >&2
  exit 1
fi

TARGET_NAME="ssh_tailnet_knownhosts"
TARGET_FILENAME="${TARGET_NAME}.rb"
TARGET_FULLPATH="${TARGET_DIR}/${TARGET_FILENAME}"

if [[ ! -z "${GITHUB_OUTPUT}" ]]; then
  (
    echo "target_name=${TARGET_NAME}"; 
    echo "target_path=${TARGET_FULLPATH}";
    echo "target_filename=${TARGET_FILENAME}";
  ) >> "${GITHUB_OUTPUT}"
fi

echo "Generating ${TARGET_FILENAME} cask file..."

VERSION="${VERSION:-${GITHUB_REF##*/}}"

SHA_DARWIN_ARM64="$(sha256sum artifacts/archives/_ssh_tailnet_knownhosts_darwin_arm64.tar.gz | awk '{print $1}')"
SHA_LINUX_AMD64="$(sha256sum artifacts/archives/_ssh_tailnet_knownhosts_linux_amd64.tar.gz | awk '{print $1}')"
SHA_LINUX_ARM64="$(sha256sum artifacts/archives/_ssh_tailnet_knownhosts_linux_arm64.tar.gz | awk '{print $1}')"

tee "${TARGET_FULLPATH}" << EOF
# This file was generated by generate_homebrew_cask.sh. DO NOT EDIT.
cask "${TARGET_NAME}" do
  name "${TARGET_NAME}"
  desc "SSH Tailnet Known Hosts"
  homepage "https://github.com/na4ma4/go-tailnet-ssh-known-hosts"
  version "${VERSION}"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "${TARGET_NAME}"

  on_macos do
    on_arm do
      url "https://github.com/na4ma4/go-tailnet-ssh-known-hosts/releases/download/v#{version}/_ssh_tailnet_knownhosts_darwin_arm64.tar.gz"
      sha256 "${SHA_DARWIN_ARM64}"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/na4ma4/go-tailnet-ssh-known-hosts/releases/download/v#{version}/_ssh_tailnet_knownhosts_linux_amd64.tar.gz"
      sha256 "${SHA_LINUX_AMD64}"
    end
    on_arm do
      url "https://github.com/na4ma4/go-tailnet-ssh-known-hosts/releases/download/v#{version}/_ssh_tailnet_knownhosts_linux_arm64.tar.gz"
      sha256 "${SHA_LINUX_ARM64}"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/_ssh_tailnet_knownhosts"]
    end
  end

  # No zap stanza required
end
EOF

echo "Generated ${TARGET_FILENAME}"
